### ISSUE TITLE
Data Issues with Demo Mode (Stats Page)

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#120]
**Outstanding:**
- Please can we make it so 'Demo Course' appears as a title - like how it is done on Android? See below:
<img src="https://cloud.githubusercontent.com/assets/5815497/24861682/834bff5c-1df1-11e7-8fe7-be1e0ebe35df.jpg" width="300">

**Fixed:**

- Demo course has no data (with any option).

- Selecting 'All Activity' and 'Last 30 days' on iOS doesn't work (it does on Android).

- Demo101 and Demo102 no data displayed on iOS for 'Last 30 days'. Works on Android.

- Demo102 and Demo 102 unable to compare to demo user 2 using any filter. Issue on iOS. 

- Whenever 'All Activity' is selected from module please reset 'compare to' option back to 'No One'.

- Paul has managed to delete the target from the demo version. Can we re-add this and ensure this isn't possible in future?

**Comment by mparker-tbox** [comment]
Demo course fixed in Android (no data should be coming from this as it's not a module). It's centralised in the list and doesn't respond to a tap).

Demo101 and Demo102 compare to 'Average' broken on both platforms for any time period. 
**Still having issues with 7 days but 30d is fixed**

Demo101 and Demo 102 unable to compare to 'Demo User2' for 'Last 7 days', works for 'Last 30 days'. Impacts both iOS and Android.
**still having issues on 7 days but 30d is fixed**

**Comment by tomglanville** [comment]
Had a look through and it appears now that only 4. is outstanding - have updated initial comment.

**Comment by tomglanville** [comment]
Final fix has been made to **feature/demo-mode-fix ***branch and merged into develop via PR.
