### ISSUE TITLE
Improve check-in flow when location services are disabled

### ISSUE THREAD

**Issue by tomglanville** [jiscdev/study-goal#150]
Feedback:

> The issue is that having typed in your code, the location pop-up shows, then once enabled you have to type the code again (but this isn't apparent).
> 
> So perhaps:
> Prevent code entry until location on
> Or ask to re-enter code

@TherapyBox Could we please keep the code on the screen whilst the user enables location services?

**Comment by TherapyBox** [comment]
Primarily an android issue.

Check-in in develop checks for location services before the user enters a number. if the user presses cancel then presses a number anyway, they are again invited to go to settings and turn on Lcoation services. When they re-enter the app, number is in the main window and pressing send pin will send the pin for checking. 

2 small issues. (1) "Send pin" needs text change to "Send PIN". (2) App takes user through to the specific study goal settings rather than location services settings, which would be preferable. We will resolve this.

**Comment by TherapyBox** [comment]
Android now runs a permission check before user enters the PIN number. Hopefully this should resovle any issues, but let me know if you'd like changed further (visible in develop branch)

**Comment by tomglanville** [comment]
Done
